// SUBMISSION TYPES
export const FETCH_SUBMISSIONS_START = 'FETCH_SUBMISSIONS_START';
export const FETCH_SUBMISSIONS_SUCCESS = 'FETCH_SUBMISSIONS_SUCCESS';
export const FETCH_SUBMISSIONS_FAILED = 'FETCH_SUBMISSIONS_FAILED';

// PLANO TYPES
export const FETCH_PLANOS_START = 'FETCH_PLANOS_START';
export const FETCH_PLANOS_SUCCESS = 'FETCH_PLANOS_SUCCESS';
export const FETCH_PLANOS_FAILED = 'FETCH_PLANOS_FAILED';

//AUTH TYPES
export const AUTH_START = 'AUTH_START';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const SET_AUTH_REDIRECT_PATH = 'SET_PURCHASE_REDIRECT_PATH';

